Algoritmo "Exibir Mensagem"
// 
// Disciplina : [Lógica de Programação e JavaScript]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Natã Pedro da Silva
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Jailson - Osasco")
Escreval ("Equipe 04")
ESCREVAL ("Abner")


Fimalgoritmo