Algoritmo "Exercicio 5"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Aqui você descreve
// Autor(a) : Natã Pedro da Silva
// Data atual : 02/09/2021
Var
// Seção de Declarações das variáveis
cont, acum:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto cont<15 faca
se acum = 0 entao
Escreval(1)
acum<-3
senao
acum<-acum*3
fimse
cont<-cont+1
escreval(acum)
fimenquanto
Fimalgoritmo