Algoritmo "cem pirmeiros inteiros"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson 
// Descrição   : (1+2 até..100)
// Autor(a)    : Natã Pedro da Silva
// Data atual  : 02/09/2021
Var
// Seção de Declarações das variáveis 
cont,acul:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto (cont<101) faca
acul<-cont+acul
cont<-cont+1
fimenquanto
Escreval("A soma dos cem primeiros números inteiros é ",acul)
Fimalgoritmo