Algoritmo "Tabuada"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson 
// Descrição   : Exibe a tabuada de um número
// Autor(a)    : Natã Pedro da Silva
// Data atual  : 02/09/2021
Var
// Seção de Declarações das variáveis 
cont,num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número inteiro: ")
Leia(num)
enquanto (cont<10) faca
cont<-cont+1
Escreval(num," *",cont," =",cont*num)
fimenquanto
Fimalgoritmo